### ISSUE TITLE
代码高亮未完全覆盖问题

### ISSUE THREAD

**Issue by liu839** [whpu-aa/website#45]
@Mamba-ZJP 大佬速来！！！！
@crupest  大佬有建议也可以提提

**在常规情况下应该呈现的**
![image](https://user-images.githubusercontent.com/64195205/101639538-63308280-3a6a-11eb-8180-33e101a101d0.png)
**BUG状态**
![image](https://user-images.githubusercontent.com/64195205/101639623-7b080680-3a6a-11eb-8cc2-b91930de9f74.png)

**简介原理**
在代码编辑器实现中我采用了一个textarea区域能够写代码，同时绑定一个值，该值额外绑定了一个div pre code区域用来高亮显示页面。

**分析问题**
我在高亮显示区域绑定名为move 的class, 采用绝对定位使该区域和整个代码区域大小一致，包括左侧横条也用placeholder进行不显示的填充使整体区域一致大小。
利用绝对定位把move 拿出文档流后 使用pre相对定位来修改到和代码区域重叠。
这时候就出现了问题，在**未接触**边界时一切正常，**接触边界后**
![image](https://user-images.githubusercontent.com/64195205/101641049-3bdab500-3a6c-11eb-8aad-1cc0aaff19d5.png)

此时问题并不是无法解决，在继续缩小的过程中 在宽度达到540px左右阶段会出现
![image](https://user-images.githubusercontent.com/64195205/101642347-db4c7780-3a6d-11eb-8e63-df7b9b0fd368.png)
显示行数的竖条莫名其妙隐藏了，而且是随着随着缩小一点点左移的

**猜测原因**
1.由于pre父级定位为绝对定位，在左移时脱离文档流，直接移出边界
2.flex布局影响

由于错误已经无法避免，而且解决很可能涉及到更换定位形式与方法，
耗时可能较长。
目前我做了一个掩耳盗铃的手段来尽量减少影响
![image](https://user-images.githubusercontent.com/64195205/101642115-91fc2800-3a6d-11eb-988a-459228ddf73f.png)
通过分三段媒体查询来保证
最终无影响
![image](https://user-images.githubusercontent.com/64195205/101642579-1f3f7c80-3a6e-11eb-9e9a-6eedda9a4664.png)

最初无影响
![image](https://user-images.githubusercontent.com/64195205/101642626-2c5c6b80-3a6e-11eb-8ec3-93b149687ffc.png)

中间尽量降低影响
![image](https://user-images.githubusercontent.com/64195205/101642723-472ee000-3a6e-11eb-8033-48b7f8343dbb.png)

**Comment by crupest** [comment]
稍微看了一下，可能是因为flex的子元素默认的shrink是1会在空间不足是自动缩小。

**Comment by liu839** [comment]
> 稍看了一下，可能是因为flex的子元素默认的收缩是1会在空间不足时自动缩小。

给 .rows 添加属性flex-shrink:0;
无效，依旧会缩进左边

**Comment by crupest** [comment]
> > 稍看了一下，可能是因为flex的子元素默认的收缩是1会在空间不足时自动缩小。
> 
> 给 .rows 添加属性flex-shrink:0;
> 无效，依旧会缩进左边

要在子元素上添加。

**Comment by liu839** [comment]
> > > 稍看了一下，可能是因为flex的子元素默认的收缩是1会在空间不足时自动缩小。
> > 
> > 
> > 给 .rows 添加属性flex-shrink:0;
> > 无效，依旧会缩进左边
> 
> 要在子元素上添加。
![image](https://user-images.githubusercontent.com/64195205/101981576-f48d3800-3ca8-11eb-95a2-82ff810d3707.png)
此为父元素，子元素即为.rows

**Comment by crupest** [comment]
你要在填充行号那一列的空间的那个元素上把`flex-shrink`设成0，不是其他的元素。

**Comment by liu839** [comment]
**第三次**尝试给rows 元素设置flex-shrink =0
![image](https://user-images.githubusercontent.com/64195205/102502974-3576b980-40ba-11eb-8b11-5b8661a2c219.png)
效果如下
![image](https://user-images.githubusercontent.com/64195205/102503198-6fe05680-40ba-11eb-9c76-f1fa0ca61e55.png)
css如下
![image](https://user-images.githubusercontent.com/64195205/102503276-825a9000-40ba-11eb-8ded-2274ff764cca.png)
**bug尚未解决**

**Comment by crupest** [comment]
你还没懂我的意思，不是行号那个元素，是填充行号空白的那个元素。

**Comment by liu839** [comment]
> 你还没懂我的意思，不是行号那个元素，是填充行号空白的那个元素。


已验证，无效。bug依旧存在。
而且这个BUG不只是一部分
是分两部分的
一部分是 .rows元素会移出屏幕导致的不匹配
另一部分是。.move元素会随着缩小直接无限（目前来说是的）左移
两者导致的元素覆盖不匹配问题不同。
![image](https://user-images.githubusercontent.com/64195205/102510900-1f212b80-40c3-11eb-974d-de7a1428f619.png)
如图，在放大到一定层次上.move（abs定位）的元素会持续左移

在代码块区域.row左移缩进去之后代码区域（textarea区域）会固定，而.move（abs绝对定位）的内部微调平移元素pre
（rel相对定位）无限左移

**Comment by liu839** [comment]
该BUG已解决，
分析：absolute定位元素宽度由内部决定，而内部之前设置的是绝对大小width，外部的textarea区域虽然也是width但是会由于窗口变动导致width变化，给textarea设置min-width解决。

**Comment by liu839** [comment]
该BUG已解决，
分析：absolute定位元素宽度由内部决定，而内部之前设置的是绝对大小width，外部的textarea区域虽然也是width但是会由于窗口变动导致width变化，给textarea设置min-width解决。
